import 'package:isar_community/isar.dart';

part 'community.g.dart';

@Collection()
class Community {
  Community({
    required this.communityId,
    required this.name,
    required this.description,
    this.rules,
    required this.city,
    required this.state,
    required this.country,
    required this.createdAt,
    required this.updatedAt,
  });

  // ------------------
  // Isar Fields
  // ------------------

  Id isarId = Isar.autoIncrement; // PK, auto-generated by Isar

  @Index(unique: true)
  String communityId; // Unique identifier

  String name;
  String description;
  String? rules;

  @Index()
  String city;
  String state;
  String country;

  DateTime createdAt;
  DateTime updatedAt;

  // ------------------
  // Firestore JSON Mapping
  // ------------------

  factory Community.fromJson(Map<String, dynamic> json) {
    return Community(
      communityId: json['communityId'] as String,
      name: json['name'] as String,
      description: json['description'] as String,
      rules: json['rules'] as String?,
      city: json['city'] as String,
      state: json['state'] as String,
      country: json['country'] as String,
      createdAt: (json['createdAt'] as DateTime),
      updatedAt: (json['updatedAt'] as DateTime),
    )..isarId = json['isarId'] as int;
  }

  Map<String, dynamic> toJson() {
    return {
      'communityId': communityId,
      'name': name,
      'description': description,
      'rules': rules,
      'city': city,
      'state': state,
      'country': country,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }
}