// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACYdEg5lr_d750EOIxfezuJDOmHuWsRHQ',
    appId: '1:385224986719:web:c7a37186a38170b9114bea',
    messagingSenderId: '385224986719',
    projectId: 'crisis-response-app-98560',
    authDomain: 'crisis-response-app-98560.firebaseapp.com',
    storageBucket: 'crisis-response-app-98560.firebasestorage.app',
    measurementId: 'G-SJLJ563K80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43teAqEHTMAw0vvCN9q9Duq0u8gVF8WE',
    appId: '1:385224986719:android:b71761bb65d9d53b114bea',
    messagingSenderId: '385224986719',
    projectId: 'crisis-response-app-98560',
    storageBucket: 'crisis-response-app-98560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZN-C0vQVe-uaPcfuVJ8lvln6MTO2BtI',
    appId: '1:385224986719:ios:334d716671bdcf65114bea',
    messagingSenderId: '385224986719',
    projectId: 'crisis-response-app-98560',
    storageBucket: 'crisis-response-app-98560.firebasestorage.app',
    iosBundleId: 'com.neatcapstone.app.emergencyResponseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZN-C0vQVe-uaPcfuVJ8lvln6MTO2BtI',
    appId: '1:385224986719:ios:334d716671bdcf65114bea',
    messagingSenderId: '385224986719',
    projectId: 'crisis-response-app-98560',
    storageBucket: 'crisis-response-app-98560.firebasestorage.app',
    iosBundleId: 'com.neatcapstone.app.emergencyResponseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACYdEg5lr_d750EOIxfezuJDOmHuWsRHQ',
    appId: '1:385224986719:web:5ece2fe6a0662a6f114bea',
    messagingSenderId: '385224986719',
    projectId: 'crisis-response-app-98560',
    authDomain: 'crisis-response-app-98560.firebaseapp.com',
    storageBucket: 'crisis-response-app-98560.firebasestorage.app',
    measurementId: 'G-4EGP3F6P23',
  );
}
